### ISSUE TITLE
mklocal.py won't download images if one present.

### ISSUE THREAD

**Issue by desepticon** [MilhouseVH/texturecache.py#56]
I've been trying to make changes to my artwork using the library manager in Maraschino (same issue happens if I use Chorus2, or even through the Kodi GUI). This works, and changes are reflected in my library. However, I can't seem to be able to figure out how to use your tool to get the selected artwork to become exported to my media folders. Thank you for helping me with the other issue. I believe the problem was on my end with my files.

This is the command I am using:

`./texturecache.py jd movies | ./tools/mklocal.py --local / --prefix / --artwork fanart poster --output ./fixup.dat --info -v`

I have tried this procedure both with, and without, the --nokeep argument. If a media file is already present, it shows this, and does _not_ download. How can I get it to overwrite already existing artwork?

[pastebin](https://pastebin.com/TRm2JTVs)

If a media artwork file isn't present it shows this, and it _does_ download:

[pastebin](https://pastebin.com/dHecZpuZ)

However if I run:

`cat fixup.dat | ./texturecache.py set`

It just puts the original artwork back, no matter what I try! Even if I delete the artwork, and the tool does indeed download the file. At first, I though artwork beef was somehow interfering. So, I disabled that. But, this issue persists. Could the issue be with my [advancedsettings.xml](https://pastebin.com/kBncMjBZ)? I did add some fields so that it automatically parses artwork.

[this](https://pastebin.com/kSYVF4AJ) is the contents of my fixup.dat

Thank you again for trying to help me with the other issue. Your help is greatly appreciated. Please let me know if I can clarify anything further.

**Comment by MilhouseVH** [comment]
There's currently no way to force `mklocal.py` to overwrite existing local artwork. The point of `mklocal.py` is to download remote artwork creating local artwork (if the local file doesn't already exist), and/or to associate your movie with the local artwork (replacing any remote artwork).

So in your case, as you already have local artwork, there's no need for `mklocal.py` to download anything - it just needs to associate your movie with the local file. Which is what it does.

And when you delete the local file, `mklocal.py` then downloads the artwork again, and proceeds to associate the movie with the local file (by writing the association instructions to `fixup.dat`).

> It just puts the original artwork back

Your movie currently refers to remote artwork, and not the local file you have downloaded (which Kodi will otherwise ignore). The contents of `fixup.dat` will change your media library so that it references the local file, not the remote file.

It looks to me as though `mklocal.py` is working correctly, what were you expecting it to do?

**Comment by desepticon** [comment]
What I would like to be able to do is set my artwork as I like after the scrapers have got to them. Sometimes they download artwork I like, sometimes they don't. I then like to go and change the artwork using either the menus in the Kodi gui, or through Chorus2, or Marachino's Library Manager.

This changes the artwork in Library views fine enough, but I would like to have the ability to export my changes to the filesystem along with their corresponding media. I recently had to nuke most of my artwork after making the mistake of exporting all my artwork from Kodi, not realizing this was only exporting the inferior cached versions. After a few of time of doing this, recaching, and exporting again - a lot of my artwork became very poor in quality. To fix this will be a tedious process, as I have of 3000 movies and 500 tv shows. Although I have already started over before finding your tool, I would like to have an easy way to get back up to speed in the future, should something happen to my database.

I am will soon be in the process of adding back my custom artwork, after letting the scrapers do the major work. Going forward, I would like to have the ability to have my custom changes saved and backed-up alongside my media.

There probably is a way to script the output from mklocal to delete the changed artwork by piping from  a dry run, and then run it again to save my changes. I'm not very good at scripting though, so it would be hard for me to figure that out.

Also, I though what the command `cat fixup.dat | ./texturecache.py set` would do, would be to cement these changes into the Kodi database. So the url of the new artwork would replace the old one in the library. And if I exported my nfo's again, these changes would be reflected. Thats not what it does though?

**Comment by MilhouseVH** [comment]
I'll give some thought to adding an `--overwrite` option so that anything that is downloaded will overwrite existing files.

However the `mklocal.py` script is very simple (stupid, even) as it will only download the remote artwork that is referenced by your media library, and/or associate your media library with a local file - it has no idea which of the two you might prefer, and for that you'll need a more sophisticated tool such as Artwork Beef which should be able to download local artwork.

If you have already downloaded artwork then used a tool to choose different artwork (or exported your entire library using Kodi) then yes, at the moment `mklocal.py` won't help you because it finds the local artwork and refuses to overwrite it.

I'll add the `--overwrite` option, maybe tomorrow, but obviously if used unwisely this could cause more problems than it solves...

> But even if I change the artwork using a library manager and delete the local artwork, and mklocal does download the proper file that I changed, running the above "cat fixup.dat" command just puts the original artwork back. Thats definitely not what I want.

`mklocal.py` will only attempt to change a movie association by adding an instruction to `fixup.dat` if the movie is not currently associated with the local file url.

In the examples you gave earlier, the current fanart movie url is:
```
http://cf2.imgobject.com/t/p/original/s6bKy6vSDy8qJ76qLw7cSX4yooG.jpg
```
and `mklocal.py` is correctly changing this association to:
```
/Volumes/wd.4tb.2/Movies/6th.Day,.The.2000.1080p.Blu-ray.HD.H264.DTS-FoRM/The.6th.Day.2000.1080p.Blu-ray.HD.H264.DTS-FoRM-fanart.jpg
```

If you then use another tool to pick different artwork which uses yet another remote url, then the next time you run `mklocal.py` it's not going to download anything, and will just re-associate your movie with the existing local file.

It sounds like you're using multiple tools that kind of do similar things and yes, they're getting in each others way. Use a tool that also creates and associates local files, or configure all of your artwork (which will likely be remote) and then once you're happy, use `mklocal.py` to download it and "lock it" into place by switching from remote urls to local urls.

**Comment by MilhouseVH** [comment]
Adding `--overwrite` may have been a little easier than I thought. Can you try this version of `mklocal.py` - download it and replace your existing version: http://ix.io/1Cqs - it adds the `--overwrite` option. Let me know if it works.

**Comment by desepticon** [comment]
So, there's no way to have the remote url changed to the new file's remote url? If you added a --overwrite option, that would be a big help though, then at least I could have the new art backed-up.

[This](https://www.dropbox.com/s/wjcwe2i5t3zbtwe/Whathappens.mp4?dl=0) is a video of what I'm trying to do, by the way.

Thank you so much for your assistance.

**Comment by desepticon** [comment]
> Adding `--overwrite` may have been a little easier than I thought. Can you try this version of `mklocal.py` - download it and replace your existing version: http://ix.io/1Cqs - it adds the `--overwrite` option. Let me know if it works.

I'll give it a shot.

**Comment by MilhouseVH** [comment]
Actually this is a slightly different implementation, please try this version: http://ix.io/1Cqt

**Comment by desepticon** [comment]
Okay. So the new version seemed to work. Only overwrote the files I made a custom change on. Great! Thanks so much.

[Link to relevant logs](https://pastebin.com/wJNuTb3V)

As you can see, it only overwrote a changed file but didn't touch another entry that didn't change. Perfect!

So where I'm a little fuzzy still is exactly what the `cat fixup.dat | ./texturecache.py set` command is doing and why it's reverting my changes. Is there no way to automagically change the library's artwork url so the changes are reflected if I export my nfo's?

**Comment by desepticon** [comment]
Oh wait. missed your new version. Ill try that one too.

**Comment by desepticon** [comment]
> http://ix.io/1Cqt

Yup. That worked too.

[Relevant logs](https://pastebin.com/pMGvFFEQ)

**Comment by MilhouseVH** [comment]
New version of `mklocal.py` with `--overwrite` option pushed.

**Comment by desepticon** [comment]
Thanks again!
